version: "3"
services:
  jupyter-opencv:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/home/jovyan/work
      ports:
        - 8888:8888
      container_name: jupyter-opencv